<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Initial schema: cycle_run, found_deal, posted_deal.
 * All money columns (*_cents) and percent columns (*_pct) are integer.
 */
final class Version20260601071824 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create cycle_run, found_deal and posted_deal tables (integer-cents money).';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE cycle_run (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, finished_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, raw_count INT NOT NULL, surviving_count INT NOT NULL, snapshotted_count INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE found_deal (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, asin VARCHAR(16) NOT NULL, title TEXT NOT NULL, image_url TEXT DEFAULT NULL, keepa_avg90_cents INT DEFAULT NULL, keepa_drop_pct INT DEFAULT NULL, snapshot_price_cents INT DEFAULT NULL, availability VARCHAR(64) DEFAULT NULL, condition VARCHAR(64) DEFAULT NULL, merchant_id VARCHAR(64) DEFAULT NULL, amazon_savings_pct INT DEFAULT NULL, saving_basis_type VARCHAR(64) DEFAULT NULL, has_deal_details BOOLEAN DEFAULT NULL, violates_map BOOLEAN DEFAULT NULL, affiliate_url TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, cycle_run_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_680CF1245946B1C4 ON found_deal (cycle_run_id)');
        $this->addSql('CREATE INDEX idx_found_deal_asin ON found_deal (asin)');
        $this->addSql('CREATE TABLE posted_deal (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, asin VARCHAR(16) NOT NULL, price_cents INT NOT NULL, posted_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_posted_deal_asin ON posted_deal (asin)');
        $this->addSql('ALTER TABLE found_deal ADD CONSTRAINT FK_680CF1245946B1C4 FOREIGN KEY (cycle_run_id) REFERENCES cycle_run (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE found_deal DROP CONSTRAINT FK_680CF1245946B1C4');
        $this->addSql('DROP TABLE cycle_run');
        $this->addSql('DROP TABLE found_deal');
        $this->addSql('DROP TABLE posted_deal');
    }
}
